import { QCMItem } from "./types";

export const GLUCIDES_QCMS: QCMItem[] = [
{ q: "Les glucides se caractérisent par :", r: ["Fonctions alcool", "Fonction aldéhyde/cétone", "Pas de carbone asymétrique", "Structure ramifiée"], c: ["A","B"] },
{ q: "Rôles structuraux des glucides :", r: ["Cellulose", "Chitine", "Muréine", "Vitamine C"], c: ["A","B","C"] },
{ q: "Rôle de réserve :", r: ["Glycogène", "Amidon", "Cellulose", "Saccharose"], c: ["A","B"] },
{ q: "Oses :", r: ["Non hydrolysables", "Formule CH2O_n", "Toujours aldéhydes", "Aldoses ou cétoses"], c: ["A","B","D"] },
{ q: "Nombre de carbones :", r: ["Tétrose = 4", "Hexose = 6", "Pentose = 3", "Heptose = 7"], c: ["A","B","D"] },
{ q: "Dihydroxyacétone :", r: ["Cétotriose", "Carbone asymétrique", "Inactive optiquement", "Ose de base cétoses"], c: ["A","C","D"] },
{ q: "Série D/L :", r: ["OH à droite", "Majorité D", "D = dextrogyre", "Indépendant rotation"], c: ["A","B","D"] },
{ q: "Épimères :", r: ["Diffèrent d'un carbone", "Toujours D", "Interconvertibles", "Même formule brute"], c: ["A","C","D"] },
{ q: "Interconversion :", r: ["Aldose→cétose", "Milieu alcalin", "Irréversible", "Glucose⇌Fructose"], c: ["A","B","D"] },
{ q: "Mutarotation :", r: ["Pouvoir rotatoire change", "α↔β", "Que cétohexoses", "Carbone anomérique"], c: ["A","B","D"] },
{ q: "Cyclisation :", r: ["Pont oxydique", "Nouveau carbone asymétrique", "Cycle 6 sommets seul", "Pyranose/furanose"], c: ["A","B","D"] },
{ q: "Propriétés physiques :", r: ["Solubles", "Absorption IR", "Pouvoir rotatoire", "Résistent chaleur"], c: ["A","B","C"] },
{ q: "Molisch :", r: ["Aldoses+cétoses", "α-naphtol", "Rouge violacé", "Spécifique désoxypentoses"], c: ["A","B","C"] },
{ q: "Réduction oses :", r: ["Un polyol", "NaBH4", "Réversible", "Ostitols"], c: ["A","B","D"] },
{ q: "Oxydation douce :", r: ["Aldéhyde→aldarique", "Aldéhyde→aldonique", "Gluconique", "Alcool→uronique"], c: ["B","C"] },
{ q: "Oxydation forte :", r: ["Groupe aldéhyde+alcool", "Diacide", "Acide glucarique", "Sans rupture cétoses"], c: ["A","B","C"] },
{ q: "Esters phosphoriques :", r: ["Intermédiaires", "G6P", "AMPc", "Sans rôle énergétique"], c: ["A","B","C"] },
{ q: "Osazones :", r: ["3 phénylhydrazines", "Caractéristiques", "À froid", "Jaunes"], c: ["A","B","D"] },
{ q: "Ribose :", r: ["Nucléotides", "β-ribofuranose ARN", "Dans ADN identique", "R-5-P"], c: ["A","B","D"] },
{ q: "Glucose :", r: ["Le plus répandu", "+52°", "38 ATP", "Éthanol levure"], c: ["A","B","C","D"] },
{ q: "Un holoside contient :", r: ["Uniquement des oses", "Ose + aglycone", "Toujours un pentose", "Jamais de liaison O-glycosidique"], c: ["A"] },
{ q: "Les liaisons O-glycosidiques unissent :", r: ["Une fonction alcool et anomérique", "Deux fonctions anomériques", "Deux carbones secondaires", "Un acide aminé et un ose"], c: ["A","B"] },
{ q: "Le saccharose est :", r: ["Non réducteur", "Composé de glucose + fructose", "Un disaccharide", "Un cétose pur"], c: ["A","B","C"] },
{ q: "Le lactose :", r: ["Est réducteur", "Contient du galactose", "A une liaison β(1→4)", "Est un trioside"], c: ["A","B","C"] },
{ q: "Le maltose est formé de :", r: ["Deux glucose", "Liaison α(1→4)", "Un fructose", "Un ose phosphorylé"], c: ["A","B"] },
{ q: "L'amidon est constitué de :", r: ["Amylose", "Amylopectine", "Cellulose", "Chitine"], c: ["A","B"] },
{ q: "L'amylose :", r: ["Est linéaire", "Possède des liaisons α(1→4)", "Est très ramifiée", "Donne bleu avec iode"], c: ["A","B","D"] },
{ q: "L'amylopectine :", r: ["Ramifiée", "Branches α(1→6)", "Détection rouge-violet à l'iode", "Polymer résistant"], c: ["A","B"] },
{ q: "Le glycogène :", r: ["Très ramifié", "Plus ramifié que l’amylopectine", "Stocké dans le foie", "Peu présent chez l'humain"], c: ["A","B","C"] },
{ q: "La cellulose :", r: ["Linéaire", "β(1→4)", "Digérable par l'humain", "Présente dans végétaux"], c: ["A","B","D"] },
{ q: "La chitine contient :", r: ["N-acétylglucosamine", "Liaisons β(1→4)", "Azote", "Galactose"], c: ["A","B","C"] },
{ q: "Les glycosaminoglycanes :", r: ["Sulfatés", "Acides", "Présents dans cartilage", "Uniquement des hexoses"], c: ["A","B","C"] },
{ q: "L'acide hyaluronique :", r: ["Lubrifiant", "Non sulfaté", "Extrêmement hydraté", "Protéine structurale"], c: ["A","B","C"] },
{ q: "Les protéoglycanes :", r: ["Protéine + GAG", "Très hydrophiles", "Dans matrice extracellulaire", "Jamais sulfatés"], c: ["A","B","C"] },
{ q: "Une liaison N-glycosidique se fait sur :", r: ["Asparagine", "Sérine", "Thréonine", "Tyrosine"], c: ["A"] },
{ q: "Une liaison O-glycosidique se fait sur :", r: ["Sérine", "Thréonine", "Asparagine", "Méthionine"], c: ["A","B"] },
{ q: "Les hétérosides contiennent :", r: ["Ose + aglycone", "Toujours un lipide", "Souvent un polyphénol", "Jamais de fonction aldéhyde"], c: ["A"] },
{ q: "Les cardiotoniques sont des :", r: ["Hétérosides", "Toxiques", "Molécules stéroïdiennes", "Amines biogènes"], c: ["A","B","C"] },
{ q: "Les saponines :", r: ["Hémolytiques", "Mousse à l'eau", "Hétérosides", "Polyphosphates"], c: ["A","B","C"] },
{ q: "Les anthocyanosides :", r: ["Pigments", "pH-dépendants", "Flavonoïdes", "Protéiques"], c: ["A","B","C"] },
{ q: "Les osamines :", r: ["Aminés", "Présents dans chitine", "Modifications d'oses", "Polyacides"], c: ["A","B","C"] },
{ q: "N-acétylglucosamine est :", r: ["Une osamine", "Composant de chitine", "Présent dans GAG", "Un cétose"], c: ["A","B","C"] },
{ q: "L'acide sialique :", r: ["Acide", "Neu5Ac", "Extrémité des glycoprotéines", "Réducteur"], c: ["A","B","C"] },
{ q: "Les glycoprotéines :", r: ["Oligosaccharides courts", "Chaîne protéique majoritaire", "Liaisons N ou O", "Uniquement animales"], c: ["A","B","C"] },
{ q: "Hémagglutinine virale reconnaît :", r: ["Acide sialique", "Mannose", "Galactose", "Cellulose"], c: ["A"] },
{ q: "La fermentation alcoolique :", r: ["Levure", "Produit éthanol", "Produit CO2", "Nécessite O2"], c: ["A","B","C"] },
{ q: "Les pentoses :", r: ["Ribose", "Désoxyribose", "Arabinose", "Acide glucuronique"], c: ["A","B","C"] },
{ q: "Les cétoses :", r: ["Fructose", "Dihydroxyacétone", "Ribulose", "Galactose"], c: ["A","B","C"] },
{ q: "Les aldoses :", r: ["Glucose", "Galactose", "Ribose", "Fructose"], c: ["A","B","C"] },
{ q: "Un ose réducteur :", r: ["Ouvre le cycle", "Réduit Ag+", "Réagit au Fehling", "Toujours pyranose"], c: ["A","B","C"] },
{ q: "Forme furanose :", r: ["5 sommets", "Fructose fréquent", "Cycle instable", "Présent dans ARN"], c: ["A","B","D"] },
{ q: "Forme pyranose :", r: ["6 sommets", "Glucose majoritaire", "Cycle stable", "Jamais anomérique"], c: ["A","B","C"] },
{ q: "Les polyols :", r: ["Sorbitol", "Mannitol", "Glycérol", "Éthanol"], c: ["A","B","C"] },
{ q: "Le sorbitol provient de :", r: ["Glucose", "Fructose", "Galactose", "Ribose"], c: ["A"] },
{ q: "Galactitol provient de :", r: ["Galactose", "Lactose", "Maltose", "Ribose"], c: ["A"] },
{ q: "La filiation des aldoses débute par :", r: ["Glycéraldéhyde", "DHA", "Fructose", "Érythrose"], c: ["A"] },
{ q: "Test Fehling positif pour :", r: ["Glucose", "Lactose", "Ribose", "Saccharose"], c: ["A","B","C"] },
{ q: "Le saccharose est négatif car :", r: ["Non réducteur", "Pas de carbone anomérique libre", "Cétose pur", "Forme linéaire"], c: ["A","B"] },
{ q: "Réaction de Tollens :", r: ["Argent", "Ose réducteur", "Dépôt miroir", "Test ADN"], c: ["A","B","C"] },
{ q: "Les glucides sont :", r: ["Énergétiques", "Structuraux", "Signaux cellulaires", "Non métabolisés"], c: ["A","B","C"] },
{ q: "Les hexoses incluent :", r: ["Glucose", "Galactose", "Fructose", "Ribose"], c: ["A","B","C"] },
{ q: "Un diholoside :", r: ["2 oses", "Hydrolysable", "Liaison glycosidique", "Toujours réducteur"], c: ["A","B","C"] },
{ q: "L'inuline est :", r: ["Polyfructose", "Végétale", "Réserve", "Azotée"], c: ["A","B","C"] },
{ q: "L'héparine :", r: ["Anticoagulant", "GAG sulfaté", "Charge négative", "Protéine"], c: ["A","B","C"] },
{ q: "Acide glucuronique :", r: ["Oxydation C6", "Dérivé glucose", "Présent dans detox", "Cétose"], c: ["A","B","C"] },
{ q: "Les glykolipides :", r: ["Lipides + oses", "Membrane cellulaire", "Rôle antigénique", "Protéines"], c: ["A","B","C"] },
{ q: "Les antigènes ABO reposent sur :", r: ["Oligosaccharides", "Glycoprotéines", "Glycolipides", "ARN"], c: ["A","B","C"] },
{ q: "Lactose → hydrolyse donne :", r: ["Galactose", "Glucose", "Fructose", "Xylose"], c: ["A","B"] },
{ q: "Maltose → hydrolyse donne :", r: ["Glucose", "Galactose", "Fructose", "Mannose"], c: ["A"] },
{ q: "Saccharose → hydrolyse donne :", r: ["Glucose", "Fructose", "Galactose", "Ribose"], c: ["A","B"] },
{ q: "La mutarotation nécessite :", r: ["Solution aqueuse", "Carbone anomérique", "Interconversion α↔β", "Oxydation"], c: ["A","B","C"] },
{ q: "O-glycosyltransférase agit sur :", r: ["OH sérine/thréonine", "Asparagine", "Tyrosine", "Arginine"], c: ["A"] },
{ q: "N-glycosylation commence dans :", r: ["RE", "Golgi", "Cytosol", "Noyau"], c: ["A"] },
{ q: "O-glycosylation commence dans :", r: ["Golgi", "RE", "Mitochondrie", "Cytosol"], c: ["A"] },
{ q: "Les lectines reconnaissent :", r: ["Oses", "Lipides", "Protéines", "ADN"], c: ["A"] },
{ q: "Les sucres sont :", r: ["Hydrophiles", "Hydroxylés", "Oxydables", "Aromatiques"], c: ["A","B","C"] },
{ q: "Le test iode :", r: ["Bleu amylos", "Rouge amylopectine", "Pas glycogène", "Différencie amidon"], c: ["A","B","D"] },
{ q: "La glucokinase phosphoryle :", r: ["Glucose", "Fructose", "Galactose", "Ribose"], c: ["A"] },
{ q: "UDP-glucose est :", r: ["Activateur", "Synthèse glycogène", "Précurseur biosynthèse", "Cétone"], c: ["A","B","C"] },
{ q: "Le fructose :", r: ["Cétose", "Présent fruits", "Plus sucré que glucose", "β-L-fructose majoritaire"], c: ["A","B","C"] },
{ q: "Les polyosides :", r: ["Polymères d'oses", "Réserve", "Structure", "Acides nucléiques"], c: ["A","B","C"] },
{ q: "La cellulose résiste à :", r: ["Enzymes humaines", "Dégradation rapide", "Hydrolyse simple", "Chaleur modérée"], c: ["A","D"] },
{ q: "La chitine est :", r: ["Structure", "Insectes", "Fongique", "Oligopeptide"], c: ["A","B","C"] },
{ q: "Les sucres acides :", r: ["Acide uronique", "Acide sialique", "Charge négative", "Toujours réducteurs"], c: ["A","B","C"] }
];

export const LIPIDES_QCMS: QCMItem[] = [
{ q: "Les lipides sont des molécules :", r: ["Solubles dans l’eau", "Insolubles ou peu solubles dans l’eau", "Très solubles dans les solvants organiques"], c: ["B","C"] },
{ q: "Les graisses et huiles désignent :", r: ["Des lipides solides et liquides", "Des lipides liquides et solides"], c: ["A"] },
{ q: "Un lipide amphiphile possède :", r: ["Une tête polaire", "Une chaîne apolaire", "Un groupe hydroxyle uniquement"], c: ["A","B"] },
{ q: "Les lipides représentent environ :", r: ["10 % du poids corporel", "20 % du poids corporel", "30 % du poids corporel"], c: ["B"] },
{ q: "Rôle énergétique : 1 g de lipides équivaut à :", r: ["1 g de lipides = 4 kcal", "1 g de lipides = 9 kcal"], c: ["B"] },
{ q: "Les lipides servent de précurseurs :", r: ["Hormones stéroïdes", "Vitamines liposolubles", "Protéines membranaires"], c: ["A","B"] },
{ q: "Les lipides assurent :", r: ["Le rôle tensioactif", "L’isolation thermique", "La synthèse du glucose"], c: ["A","B"] },
{ q: "Dans la classification de Hennen, on retrouve :", r: ["Triglycérides", "Glycérophospholipides", "Acides aminés"], c: ["A","B"] },
{ q: "Les lipides vrais sont obtenus par condensation :", r: ["Acides gras + alcools", "Acides gras + amines", "Acides gras + aldéhydes"], c: ["A","B"] },
{ q: "Les lipides simples contiennent :", r: ["C, H, O", "C, H, O, N"], c: ["A"] },
{ q: "Les lipides complexes contiennent en plus :", r: ["Phosphore", "Azote", "Soufre"], c: ["A","B","C"] },
{ q: "Les lipides isopréniques sont aussi appelés :", r: ["Insaponifiables", "Lipoïdes"], c: ["A","B"] },
{ q: "Les acides gras naturels ont en général :", r: ["Une chaîne linéaire", "Un nombre pair de carbones", "Une structure aromatique"], c: ["A","B"] },
{ q: "Formule brute des acides gras saturés :", r: ["CnH2nO2", "CnH2(n–x)O2"], c: ["A"] },
{ q: "Les acides gras insaturés ont des doubles liaisons :", r: ["Toujours conjuguées", "En position malonique", "De configuration cis"], c: ["B","C"] },
{ q: "L’acide palmitique est :", r: ["C16:0", "Insaturé"], c: ["A"] },
{ q: "L'acide stéarique est :", r: ["C18:0", "Un acide gras insaturé"], c: ["A"] },
{ q: "L’acide oléique est :", r: ["C18:1(9)", "Un oméga-9"], c: ["A","B"] },
{ q: "L’acide linoléique est :", r: ["C18:2(9,12)", "Oméga-6"], c: ["A","B"] },
{ q: "L’acide linolénique est :", r: ["C18:3(9,12,15)", "Oméga-3"], c: ["A","B"] },
{ q: "L’acide arachidonique est :", r: ["C20:4", "Oméga-6"], c: ["A","B"] },
{ q: "Un acide gras hydroxylé :", r: ["Acide ricinoléique", "Acide arachidonique"], c: ["A"] },
{ q: "L'acide tuberculostéarique est :", r: ["Ramifié", "Cyclique"], c: ["A"] },
{ q: "L’acide chaulmoogrique est :", r: ["Cyclique", "Saturé"], c: ["A"] },
{ q: "La solubilité dans l’eau :", r: ["Augmente avec la longueur de la chaîne", "Diminue avec la longueur de la chaîne"], c: ["B"] },
{ q: "Les acides gras saturés fondent :", r: ["Plus haut avec une longue chaîne", "Plus bas avec une insaturation"], c: ["A","B"] },
{ q: "L'indice d’acidité permet de :", r: ["Dosage des acides gras libres", "Contrôler la qualité d’une huile"], c: ["A","B"] },
{ q: "L’indice d’iode mesure :", r: ["La quantité de doubles liaisons", "La masse molaire"], c: ["A"] },
{ q: "La saponification donne :", r: ["Savons", "Esters méthyliques"], c: ["A"] },
{ q: "Les triacylglycérols sont :", r: ["Apolaires", "Solubles dans l’eau"], c: ["A"] },
{ q: "Un TAG homogène contient :", r: ["3 acides gras identiques", "3 acides gras différents"], c: ["A"] },
{ q: "La lipase hormone-sensible libère d’abord :", r: ["Acides gras 1 et 3", "Acides gras du carbone 2"], c: ["A"] },
{ q: "La saponification d’un TAG donne :", r: ["Glycérol", "Sels d’acides gras"], c: ["A","B"] },
{ q: "Le rancissement provient :", r: ["De l’auto-oxydation des insaturations", "De l’hydrolyse enzymatique"], c: ["A"] },
{ q: "Les cérides sont :", r: ["Des monoesters", "Insolubles dans l’eau", "Très facilement hydrolysables"], c: ["A","B"] },
{ q: "Leur rôle principal est :", r: ["Protection", "Réserve énergétique"], c: ["A"] },
{ q: "Un stéride est :", r: ["Un ester d’acide gras + stérol", "Un glycérolipide"], c: ["A"] },
{ q: "Le palmitate de cholestérol est un :", r: ["Stéride", "Phospholipide"], c: ["A"] },
{ q: "Leur squelette de base est :", r: ["L’acide phosphatidique", "Le cholestérol"], c: ["A"] },
{ q: "La phosphatidylcholine est appelée :", r: ["Lécithine", "Céphaline"], c: ["A"] },
{ q: "Phosphatidyléthanolamine =", r: ["Lécithine", "Céphaline"], c: ["B"] },
{ q: "Les cardiolipides sont présents dans :", r: ["Le cœur", "Les mitochondries"], c: ["B"] },
{ q: "Les lysophospholipides sont :", r: ["Cytolytiques", "Hémolytiques"], c: ["A","B"] },
{ q: "Le PAF est :", r: ["Très hydrosoluble", "Un puissant médiateur inflammatoire"], c: ["A","B"] },
{ q: "La phospholipase A2 libère :", r: ["L’acide gras du carbone 2", "L’alcool lié au phosphate"], c: ["A"] },
{ q: "Les phospholipides sont :", r: ["Amphiphiles", "Constituants des membranes"], c: ["A","B"] },
{ q: "Ils sont surtout présents dans :", r: ["Animaux", "Végétaux"], c: ["B"] },
{ q: "Ils contiennent :", r: ["Glycérol", "Acides gras", "Un ose"], c: ["A","B","C"] },
{ q: "L’alcool de base est :", r: ["Sphingosine", "Glycérol"], c: ["A"] },
{ q: "Un céramide est :", r: ["Sphingosine + acide gras", "Glycérol + acide gras"], c: ["A"] },
{ q: "La sphingomyéline contient :", r: ["Phosphocholine", "Acides aminés"], c: ["A"] },
{ q: "Les glycosphingolipides comprennent :", r: ["Cérébrosides", "Gangliosides"], c: ["A","B"] },
{ q: "Un ganglioside contient :", r: ["Acide sialique", "Phosphate"], c: ["A"] },
{ q: "Les eicosanoïdes comprennent :", r: ["Prostaglandines", "Leucotriènes"], c: ["A","B"] },
{ q: "Ils dérivent tous :", r: ["De l’acide arachidonique", "De l’acide oléique"], c: ["A"] },
{ q: "Les stéroïdes dérivent :", r: ["Du stérane", "Du cholestérol"], c: ["A","B"] },
{ q: "Le cholestérol est :", r: ["Un stérol", "Un précurseur hormonal"], c: ["A","B"] },
{ q: "Les sels biliaires servent à :", r: ["Émulsion des lipides", "Élimination du cholestérol"], c: ["A","B"] },
{ q: "L’ergostérol est un :", r: ["Stérol végétal", "Précurseur de la vitamine D2"], c: ["A","B"] },
{ q: "La vitamine D3 dérive :", r: ["Du 7-déhydrocholestérol", "Du rétinol"], c: ["A"] },
{ q: "La vitamine A provient de :", r: ["Carotènes", "Cholestérol"], c: ["A"] },
{ q: "La vitamine E est :", r: ["Antioxydante", "Une quinone"], c: ["A"] },
{ q: "La vitamine K est nécessaire à :", r: ["La coagulation", "La vision nocturne"], c: ["A"] },
{ q: "Les lipoprotéines transportent :", r: ["Lipides", "Glucose"], c: ["A"] },
{ q: "Les plus légères sont :", r: ["HDL", "Chylomicrons"], c: ["B"] },
{ q: "Les plus riches en protéines sont :", r: ["HDL", "LDL"], c: ["A"] },
{ q: "Les apolipoprotéines servent à :", r: ["Reconnaissance cellulaire", "Transport lipidique"], c: ["A","B"] },
{ q: "Le cœur hydrophobe des lipoprotéines contient principalement :", r: ["Triglycérides", "Cholestérol libre", "Cholestérol estérifié"], c: ["A","C"] },
{ q: "La périphérie hydrophile des lipoprotéines est formée par :", r: ["Phospholipides", "Cholestérol libre", "Protéines"], c: ["A","B","C"] },
{ q: "Les apolipoprotéines jouent un rôle dans :", r: ["Structure des lipoprotéines", "Reconnaissance par des récepteurs", "Synthèse du glycogène"], c: ["A","B"] },
{ q: "Les lipoprotéines plasmatiques transportent :", r: ["Cholestérol", "Triglycérides", "ADN"], c: ["A","B"] },
{ q: "Les acides biliaires primaires sont :", r: ["Acide cholique", "Acide chénodésoxycholique", "Acide lithocholique"], c: ["A","B"] },
{ q: "Les acides biliaires secondaires proviennent :", r: ["Du foie", "De la transformation intestinale", "De la rate"], c: ["B"] },
{ q: "Les sels biliaires sont conjugués à :", r: ["Glycine", "Taurine", "Glucose"], c: ["A","B"] },
{ q: "La vitamine D résulte d’une réaction :", r: ["Thermique", "Photochimique (UV)", "Fermentative"], c: ["B"] },
{ q: "Le noyau commun des stéroïdes est :", r: ["Pyridine", "Stérane", "Cyclohexane"], c: ["B"] },
{ q: "Les hormones stéroïdes sont :", r: ["Liposolubles", "Hydrosolubles"], c: ["A"] },
{ q: "La vitamine E protège contre :", r: ["Lipoperoxydation", "Dégradation des protéines", "Stress oxydatif"], c: ["A","C"] },
{ q: "La vitamine A dérive :", r: ["De carotènes", "Du cholestérol"], c: ["A"] },
{ q: "Le rétinal est essentiel à :", r: ["La vision crépusculaire", "L’homéostasie calcique"], c: ["A"] },
{ q: "La vitamine K intervient dans :", r: ["La coagulation sanguine", "La synthèse de la rhodopsine"], c: ["A"] },
{ q: "Les ubiquinones interviennent dans :", r: ["La chaîne respiratoire mitochondriale", "La glycolyse"], c: ["A"] },
{ q: "Les plastoquinones interviennent dans :", r: ["La photosynthèse", "L’hématopoïèse"], c: ["A"] },
{ q: "La vitamine K est :", r: ["Une naphtoquinone", "Une ubiquinone"], c: ["A"] },
{ q: "L’addition d’halogènes (Br₂) mesure :", r: ["L’indice d’iode", "Le degré d’insaturation", "La masse molaire"], c: ["A","B"] },
{ q: "L’hydrogénation des acides gras insaturés conduit à :", r: ["Des acides gras saturés", "La formation de margarine", "La formation de savons"], c: ["A","B"] },
{ q: "La migration de double liaison permet d’obtenir :", r: ["Des doubles liaisons conjuguées", "Des acides gras saturés"], c: ["A"] },
{ q: "L’oxydation au KMnO₄ produit :", r: ["Glycols", "Coupure oxydante", "Saponification"], c: ["A","B"] },
{ q: "Les phospholipides sont :", r: ["Amphiphiles", "Tensioactifs", "Solubles dans l’acétone"], c: ["A","B"] },
{ q: "Ils forment dans l’eau :", r: ["Bicouches", "Micelles", "Cristaux ioniques"], c: ["A","B"] },
{ q: "Le surfactant pulmonaire contient :", r: ["90 % phospholipides", "50 % protéines", "10 % cholestérol"], c: ["A"] },
{ q: "Les plasmalogènes sont présents dans :", r: ["Tissu nerveux", "Myocarde", "Foie"], c: ["A","B","C"] },
{ q: "Le PAF contient :", r: ["Un groupement acétyle court", "3 longues chaînes d’acides gras"], c: ["A"] },
{ q: "Le PAF provoque :", r: ["Agrégation plaquettaire", "Chimiotactisme", "Hausse de la tension artérielle"], c: ["A","B"] },
{ q: "Les glycéroglycolipides sont :", r: ["Rares chez les animaux", "Abondants chez les végétaux", "Présents dans les chloroplastes"], c: ["A","B","C"] },
{ q: "Le céramide est le précurseur :", r: ["Des sphingomyélines", "Des cérébrosides", "Des gangliosides"], c: ["A","B","C"] },
{ q: "Les sulfatides sont :", r: ["Des cérébrosides sulfatés", "Des phospholipides"], c: ["A"] },
{ q: "Les gangliosides contiennent :", r: ["Acide sialique", "Phosphate"], c: ["A"] },
{ q: "Le GM2 est un :", r: ["Ganglioside", "Triglycéride"], c: ["A"] },
{ q: "Les lipides insaponifiables incluent :", r: ["Stéroïdes", "Caroténoïdes", "Glycérolipides"], c: ["A","B"] }
];

export const AMINO_QCMS: QCMItem[] = [
{ q: "Les acides aminés sont des…", r: ["Composés organiques comportant une fonction acide carboxylique", "Composés organiques comportant une fonction amine primaire", "Substances minérales", "Composés aromatiques uniquement"], c: ["A","B"] },
{ q: "Les acides aminés naturels sont des…", r: ["Acides β-aminés", "Acides α-aminés", "Acides ayant NH₂ et COOH sur le même carbone", "Acides dépourvus d’azote"], c: ["B","C"] },
{ q: "Les acides aminés jouent les rôles suivants :", r: ["Participent à la synthèse protéique", "Sont des neuromédiateurs", "Sont précurseurs d’hormones thyroïdiennes", "Ne participent à aucune synthèse biologique"], c: ["A","B","C"] },
{ q: "Les neuromédiateurs excitateurs cités dans le cours sont :", r: ["Acide aspartique", "Acide glutamique", "Glycine", "Alanine"], c: ["A","B"] },
{ q: "La glycine est un neuromédiateur :", r: ["Excitateur", "Inhibiteur", "Neutre", "Toxique"], c: ["B"] },
{ q: "La tyrosine est précurseur de :", r: ["Hormones thyroïdiennes", "Mélanine", "GABA", "Catécholamines"], c: ["A","B","D"] },
{ q: "La glycine est précurseur de :", r: ["Porphyrines", "Créatine", "Histamine", "Mélanine"], c: ["A","B"] },
{ q: "La notation des acides aminés utilise :", r: ["Trois lettres", "Une lettre", "Un code numérique", "Le suffixe « ine » dans les noms usuels"], c: ["A","B","D"] },
{ q: "Les aminoacides protéinogènes sont au nombre de :", r: ["20", "22", "18", "21"], c: ["B"] },
{ q: "Les acides aminés à radical R apolaire comprennent :", r: ["Glycine", "Valine", "Sérine", "Leucine"], c: ["A","B","D"] },
{ q: "Les acides aminés hydroxylés sont :", r: ["Tyrosine", "Sérine", "Thréonine", "Proline"], c: ["A","B","C"] },
{ q: "La cystéine contient un groupement :", r: ["Thiol", "Mercaptan", "Hydroxyle", "Amide"], c: ["A","B"] },
{ q: "La glutamine est :", r: ["L’amide de l’acide glutamique", "Transporteur d’ammoniac", "Un acide aminé essentiel", "Un acide aminé aromatique"], c: ["A","B"] },
{ q: "Les acides aminés acides sont :", r: ["Aspartique", "Glutamique", "Lysine", "Arginine"], c: ["A","B"] },
{ q: "Les acides aminés basiques comprennent :", r: ["Lysine", "Arginine", "Histidine", "Méthionine"], c: ["A","B","C"] },
{ q: "L’isomérie optique concerne tous les acides aminés sauf :", r: ["Glycine", "Valine", "Proline", "Isoleucine"], c: ["A"] },
{ q: "Les acides aminés absorbent l’UV à :", r: ["230 nm (tous les AA)", "260 nm (Phénylalanine)", "275 nm (Tyrosine)", "280 nm (Tryptophane)"], c: ["A","B","C","D"] },
{ q: "La tyrosine et le tryptophane ont une fluorescence maximale à :", r: ["300 nm (Tyr)", "340 nm (Trp)", "230 nm", "400 nm"], c: ["A","B"] },
{ q: "La forme zwitterion est :", r: ["Majoritaire au pH isoélectrique", "De charge nulle", "Présente uniquement en milieu acide", "Absente en solution"], c: ["A","B"] },
{ q: "Les acides aminés neutres ont un pHi autour de :", r: ["3", "6", "9", "12"], c: ["B"] },
{ q: "Une solution tampon d’acides aminés :", r: ["Existe grâce à l’ionisation", "Peut résister aux variations de pH", "Ne peut pas être préparée", "Est rendue possible par la présence de COOH et NH₂"], c: ["A","B","D"] },
{ q: "La réaction d’estérification du COOH produit :", r: ["Un ester", "De l’eau", "Une amide", "Un alcool"], c: ["A","B"] },
{ q: "La décarboxylation enzymatique utilise :", r: ["Le phosphate de pyridoxal", "La vitamine B6", "Le magnésium", "Une décarboxylase"], c: ["A","B","D"] },
{ q: "La dopamine provient de :", r: ["3,4-dihydroxyphénylalanine", "Sérine", "Tryptophane", "Glutamine"], c: ["A"] },
{ q: "La réaction de Sanger identifie :", r: ["L’acide aminé N-terminal", "Les acides aminés C-terminaux", "Les acides aminés libres", "Les peptides cycliques"], c: ["A"] },
{ q: "Le DNFB forme :", r: ["Dinitrophényl aminoacide", "Un dérivé jaune", "Un amide", "Un chromophore"], c: ["A","B"] },
{ q: "La réaction d’Edman utilise :", r: ["Le phényl isothiocyanate", "Le PTC", "L’identification du N-terminal", "La libération d’un PTH-AA"], c: ["A","B","C","D"] },
{ q: "La dansylation produit :", r: ["Des dérivés fluorescents", "Des sulfoamines", "Un composé violet", "Un composé bleu"], c: ["A","B"] },
{ q: "La ninhydrine détecte :", r: ["Les acides aminés", "Le pourpre de Ruhemann", "Les protéines", "Les iminoacides en jaune"], c: ["A","B","D"] },
{ q: "Les peptides sont :", r: ["Une association d’acides aminés", "Un enchaînement par liaisons peptidiques", "Des protéines complexes", "Classés en oligopeptides ou polypeptides"], c: ["A","B","D"] },
{ q: "Un peptide composé de 2 à 20 acides aminés est :", r: ["Un oligopeptide", "Un polypeptide", "Une protéine", "Une holoprotéine"], c: ["A"] },
{ q: "L'extrémité N-terminale porte :", r: ["Un groupe amine libre", "Le premier acide aminé", "Un carboxyle libre", "L’acide aminé terminal"], c: ["A","B"] },
{ q: "Le glutathion est un tripeptide formé de :", r: ["Glu", "Cys", "Gly", "Tyr"], c: ["A","B","C"] },
{ q: "La liaison peptidique est :", r: ["Rigide", "De configuration trans", "Polaire", "Une liaison simple totalement libre"], c: ["A","B","C"] },
{ q: "Deux liaisons peptidiques consécutives réagissent avec :", r: ["Le biuret", "Le cuivre", "L’acide sulfurique", "Le chlorure de Dansyle"], c: ["A","B"] },
{ q: "La trypsine coupe après :", r: ["Arginine", "Lysine", "Proline si à droite", "Phénylalanine"], c: ["A","B"] },
{ q: "La chymotrypsine coupe au niveau :", r: ["Phénylalanine", "Tyrosine", "Tryptophane", "Leucine"], c: ["A","B","C","D"] },
{ q: "Le bromure de cyanogène coupe au niveau du carboxyle de :", r: ["Méthionine", "Leucine", "Glycine", "Valine"], c: ["A"] },
{ q: "L'ocytocine est :", r: ["Un nanopeptide", "Contient un pont disulfure", "Sécrétée par la post-hypophyse", "Identique à la vasopressine"], c: ["A","B","C"] },
{ q: "La vasopressine diffère de l’ocytocine par :", r: ["Ile remplacée par Phe", "Leu remplacée par un acide aminé basique", "La même séquence exactement", "Aucun pont disulfure"], c: ["A","B"] },
{ q: "Les protéines sont des…", r: ["Macromolécules", "Formées d’acides aminés", "Lien par liaisons peptidiques", "Acides nucléiques"], c: ["A","B","C"] },
{ q: "Les protéines jouent les rôles suivants :", r: ["Catalyse enzymatique", "Stockage", "Transport", "Communication intercellulaire"], c: ["A","B","C","D"] },
{ q: "Les holoprotéines sont :", r: ["Composées uniquement d’acides aminés", "Associées à un groupement prosthétique", "Pas des protéines", "Dépourvues de peptide"], c: ["A"] },
{ q: "Les hétéroprotéines contiennent :", r: ["Un groupement prosthétique", "Un élément minéral ou organique", "Seulement des acides aminés", "Un groupement métallique"], c: ["A","B","D"] },
{ q: "Les glycoprotéines incluent :", r: ["Immunoglobulines", "Transferrine", "Haptoglobines", "Fibrinogène"], c: ["A","B","C","D"] },
{ q: "Les structures secondaires comprennent :", r: ["Hélice α", "Feuillet β", "Domaine", "Motif"], c: ["A","B"] },
{ q: "Les collagènes sont :", r: ["Protéines fibreuses", "En feuillet plissé β", "En hélice α", "Présents dans les tissus conjonctifs"], c: ["A","D"] },
{ q: "La structure tertiaire est stabilisée par :", r: ["Ponts disulfure", "Liaisons ioniques", "Interactions hydrophobes", "Liaisons peptidiques"], c: ["A","B","C"] },
{ q: "La structure quaternaire concerne :", r: ["L’association de plusieurs sous-unités", "Les protomères", "Les monomères", "Une seule chaîne"], c: ["A","B","C"] },
{ q: "La dénaturation entraîne :", r: ["Perte d’activité biologique", "Insolubilisation", "Augmentation de la viscosité", "Rupture des liaisons peptidiques"], c: ["A","B","C"] }
];

export const NUCLEIC_QCMS: QCMItem[] = [
{ q: "Les acides nucléiques sont :", r: ["Des polypeptides", "Des polynucléotides", "Constitués de nucléotides", "Unis par des liaisons phosphodiester"], c: ["B","C","D"] },
{ q: "Les deux principaux types d’acides nucléiques sont :", r: ["ADN", "ARN", "ATP", "Coenzyme A"], c: ["A","B"] },
{ q: "Les acides nucléiques jouent un rôle dans :", r: ["La réplication", "La transcription", "La traduction", "La glycogénolyse"], c: ["A","B","C"] },
{ q: "Les nucléotides entrent dans la composition de :", r: ["L’ATP", "Le NAD+", "Le CDP-choline", "La cellulose"], c: ["A","B","C"] },
{ q: "La cytosine est :", r: ["Une base purique", "Une base pyrimidique", "Une 2-hydroxy-4-amino pyrimidine", "Une base absente de l’ADN"], c: ["B","C"] },
{ q: "La thymine est :", r: ["Présente dans l’ADN", "Présente dans l’ARN", "Un 5-méthyluracile", "Une base purique"], c: ["A","C"] },
{ q: "L’uracile est :", r: ["Présent dans l’ADN", "Présent dans l’ARN", "Un dérivé de la pyrimidine", "Un 2,4-dihydroxy pyrimidine"], c: ["B","C","D"] },
{ q: "L’adénine est :", r: ["Une base purique", "Une 6-amino purine", "Absente de l’ADN", "Présente dans les ARN"], c: ["A","B","D"] },
{ q: "Les bases puriques communes sont :", r: ["Adénine", "Guanine", "Uracile", "Hypoxanthine"], c: ["A","B","D"] },
{ q: "Les bases azotées absorbent dans l’UV car :", r: ["Elles sont aromatiques", "Elles possèdent des doubles liaisons conjuguées", "Elles sont chargées négativement", "Elles sont méthylées"], c: ["A","B"] },
{ q: "Le ribose dans les acides nucléiques est sous forme :", r: ["Linéaire", "Cyclique furanique", "β-D-ribofuranose", "α-D-ribopyranose"], c: ["B","C"] },
{ q: "Le test de Bial révèle :", r: ["Le ribose", "Le désoxyribose", "Une coloration verte", "Une coloration rouge"], c: ["A","C"] },
{ q: "Les réactions de Feulgen et Dische caractérisent :", r: ["Le ribose", "Le 2-désoxyribose", "L’ADN", "L’ARN"], c: ["B","C"] },
{ q: "Les nucléosides puriques se terminent par :", r: ["-ose", "-osine", "-idine", "-amine"], c: ["B"] },
{ q: "Les nucléosides pyrimidiques se terminent par :", r: ["-ose", "-osine", "-idine", "-ylate"], c: ["C"] },
{ q: "Les nucléotides sont :", r: ["Des esters phosphoriques de nucléosides", "Des bases azotées phosphorylées", "Des nucléosides + phosphate", "Toujours triphosphates"], c: ["A","C"] },
{ q: "Un ribonucléoside peut être phosphorylé en positions :", r: ["2’", "3’", "5’", "1’"], c: ["A","B","C"] },
{ q: "Un désoxyribonucléoside peut être phosphorylé en :", r: ["3’", "5’", "2’", "1’"], c: ["A","B"] },
{ q: "L’AMP cyclique est :", r: ["Un nucléotide cyclique", "Formé entre 2’ et 3’", "Un second messager", "Un acide gras"], c: ["A","C"] },
{ q: "Le GTP peut servir pour :", r: ["Fournir de l’énergie", "L’activation de molécules", "La synthèse protéique", "La coloration Feulgen"], c: ["A","B","C"] },
{ q: "Dans les acides nucléiques, la liaison entre nucléotides est :", r: ["Peptidique", "Phosphodiester 3’→5’", "Glycosidique", "Hydrogène"], c: ["B"] },
{ q: "L'ADN s'écrit conventionnellement :", r: ["3’ → 5’", "5’ → 3’", "Par ordre alphabétique", "De façon antiparallèle"], c: ["B"] },
{ q: "L'hydrolyse alcaline :", r: ["Hydrolyse l’ARN", "Hydrolyse l’ADN", "Rupture des liaisons phosphodiester", "Nécessite l’hydroxyle en 2’"], c: ["A","C","D"] },
{ q: "Les RNases :", r: ["Coupent l'ADN", "Coupent l’ARN", "Sont spécifiques", "Coupent toujours en 5’"], c: ["B","C"] },
{ q: "La RNase Pancréatique coupe :", r: ["Au niveau des purines", "Au niveau des pyrimidines", "Libère des 3’-phosphates", "Libère des 5’-phosphates"], c: ["B","C"] },
{ q: "La DNase I (pancréatique) coupe :", r: ["Un seul brin", "Les deux brins", "Par mécanisme haplotomique", "Par mécanisme diplotomique"], c: ["A","C"] },
{ q: "Les enzymes de restriction coupent :", r: ["Au hasard", "Aux séquences palindromiques", "Les 2 brins d’ADN", "Seulement l’ARN"], c: ["B","C"] },
{ q: "Les ddNTP manquent :", r: ["De OH en 2’", "De OH en 3’", "De base azotée", "De groupement phosphate"], c: ["B"] },
{ q: "Un ddNTP incorporé dans une chaîne entraîne :", r: ["Le prolongement", "L’arrêt de la polymérisation", "Une mutation", "Un arrêt de la synthèse du brin"], c: ["B","D"] },
{ q: "Le séquençage de Sanger nécessite :", r: ["ADN matrice", "ARN polymérase", "ADN polymérase", "Une amorce"], c: ["A","C","D"] },
{ q: "Le pyroséquençage :", r: ["Utilise la lumière", "Détecte le pyrophosphate", "S’effectue sans gel", "Dépend d’une apyrase"], c: ["A","B","D"] },
{ q: "L’ADN des eucaryotes est :", r: ["Nucléaire", "Mitochondrial", "Chloroplastique", "Cytoplasmique"], c: ["A","B","C"] },
{ q: "La règle de Chargaff dit que :", r: ["A = T", "G = C", "A + G = C + T", "A = G"], c: ["A","B","C"] },
{ q: "La double hélice B d’ADN contient par tour :", r: ["5 nucléotides", "10 nucléotides", "34 Å", "3,4 Å"], c: ["B","C","D"] },
{ q: "Les deux brins d’ADN sont :", r: ["Parallèles", "Antiparallèles", "Enroulés à droite", "Enroulés à gauche"], c: ["B","C"] },
{ q: "Les paires de bases sont unies par :", r: ["Liaisons hydrogène", "Liaisons covalentes", "Interactions hydrophobes", "Liaisons peptidiques"], c: ["A","C"] },
{ q: "Le grand sillon de l’ADN permet :", r: ["L’interaction avec protéines", "L'élimination des bases", "La réplication", "Le repliement tertiaire"], c: ["A"] },
{ q: "L’ADN Z est :", r: ["Une hélice droite", "Une hélice gauche", "Majoritaire", "Minoritaire"], c: ["B","D"] },
{ q: "Les topoisomérases I :", r: ["Coupent les deux brins", "Déroulent l’ADN", "Introduisent des supertours", "Sont indispensables"], c: ["B","D"] },
{ q: "L’ADN est :", r: ["Chargé négativement", "Soluble dans l’eau", "Insoluble dans l’éthanol", "Précipité par l’alcool"], c: ["A","B","D"] },
{ q: "L’ADN absorbe à :", r: ["260 nm", "280 nm", "340 nm", "260 nm pour dosage"], c: ["A","D"] },
{ q: "Le rapport de Warburg pour un ADN pur est :", r: ["1,8 à 2", "2 à 2,2", "0,5", "10"], c: ["A"] },
{ q: "L’effet hyperchrome correspond à :", r: ["Baisse d’absorbance", "Augmentation d’absorbance", "Séparation des brins", "Fusion de l’ADN"], c: ["B","C"] },
{ q: "La température de fusion Tm dépend de :", r: ["Longueur", "Composition en bases", "Concentration en sels", "Température ambiante"], c: ["A","B","C"] },
{ q: "La dénaturation de l’ADN par chauffage est :", r: ["Irréversible", "Réversible lentement", "Due aux liaisons H", "Impossible"], c: ["B","C"] },
{ q: "L’ARN est :", r: ["Monocaténaire", "Bicaténaire", "Contient U", "Contient T"], c: ["A","C"] },
{ q: "Les ARNm représentent :", r: ["1–5% des ARN", "80% des ARN", "Sont très longs", "Sont produits par ARN polymérase II"], c: ["A","C","D"] },
{ q: "Les ARNr représentent :", r: ["80% des ARN", "15% des ARN", "Participent à la traduction", "Transportent les AA"], c: ["A","C"] },
{ q: "Les ARNt :", r: ["75–90 nucléotides", "15% des ARN", "Contiennent des bases modifiées", "Sont linéaires"], c: ["A","B","C"] },
{ q: "Le site anticodon se trouve sur :", r: ["L’ARNm", "L’ARNt", "L’ARNr", "Les ADN mitochondriaux"], c: ["B"] },
{ q: "L’extrémité 3’ de l’ARNt porte :", r: ["Un acide aminé", "Un codon", "Une méthylation", "Un phosphate libre"], c: ["A"] },
{ q: "Les ARNsn participent à :", r: ["L’épissage", "La traduction", "La maturation de l’ARNr", "La réplication"], c: ["A"] },
{ q: "Les ARNsno :", r: ["Sont nucléolaires", "Épissagent l’ARNm", "Modifient l’ARNr", "Transportent l’AA"], c: ["A","C"] },
{ q: "Les ARNmi peuvent :", r: ["Cliver un ARNm", "Bloquer la traduction", "Allonger la chaîne peptidique", "Reguler l’expression génique"], c: ["A","B","D"] },
{ q: "Le ribose rend l’ARN :", r: ["Stable", "Instable en milieu alcalin", "Résistant", "Peu soluble"], c: ["B"] },
{ q: "Les ribozymes sont :", r: ["Des enzymes protéiques", "Des ARN catalytiques", "Des ARNt", "Capables de cliver l’ARN"], c: ["B","D"] },
{ q: "L’hypoxanthine est :", r: ["Un intermédiaire de synthèse", "Une base purique", "Présente dans les nucléotides", "Une base de l’ARN"], c: ["A","B","C"] },
{ q: "La liaison N-osidique unit :", r: ["Une base et un pentose", "Une base et un phosphate", "Le N1 des pyrimidines", "Le N9 des purines"], c: ["A","C","D"] },
{ q: "Les nucléosides monophosphates cycliques :", r: ["Ont un phosphate lié à deux OH", "Peuvent être 3’,5’-AMPc", "Sont inactifs", "Participent à la régulation cellulaire"], c: ["A","B","D"] },
{ q: "La chaîne de l’ADN monte de :", r: ["3,4 Å par base", "34 Å par tour", "1 nm par base", "2,4 nm de diamètre"], c: ["A","B","D"] }
];
